apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    name: argo-cd
spec:
    destination:
        namespace: unsupervised-argocd
        server: 'https://kubernetes.default.svc'
    project: default
    source:
        chart: argo-cd
        helm:
            valueFiles:
                - >-
                    https://{{github_pac}}@raw.githubusercontent.com/local-tests/argocd-example-apps/apps/argo-cd-values.yaml
        repoURL: >-
            https://argoproj.github.io/argo-helm
        targetRevision: '3.24.0'
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        retry:
            backoff:
                duration: 5s
                factor: 2
                maxDuration: 1m
        syncOptions:
            - PruneLast=true
            - CreateNamespace=true
            - ApplyOutOfSyncOnly=true