apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: guestbook
spec:
    syncWindows:
        - kind: allow
          schedule: '0/5 * * * *'
          duration: 1h
          applications:
              - '*'
          manualSync: true
        - kind: deny
          schedule: '0 22 * * *'
          duration: 1h
          namespaces:
              - guestbook
#        - kind: allow
#          schedule: '0 23 * * *'
#          duration: 1h
#          clusters:
#              - in-cluster
#              - cluster1