apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: myapp
spec:
    syncWindows:
        - kind: allow
          schedule: '0/2 * * * *'
          duration: 1h
          applications:
              - '*'
          manualSync: true
