apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    finalizers:
        - resources-finalizer.argocd.argoproj.io
    name: argocd-test-change
spec:
    destination:
        namespace: argocd
        server: 'https://kubernetes.default.svc'
    project: default
    source:
        chart: argo-cd
        helm:
            # instead of passing in credentials, pass in the values directly as a block
            # indented block from the original values file with >- to interpret the block as a string
            values: >-
                controller:
                    args:
                        appResyncPeriod: "30"
                    extraArgs:
                        - --app-state-cache-expiration
                        - 1s
                        - --default-cache-expiration
                        - 1s
                server:
                    additionalProjects:
                        - name: default
                          namespace: argocd
                          description: Sync Windows Test
                          sourceRepos:
                              - '*'
                          destinations:
                              - namespace: '*'
                                server: '*'
                          clusterResourceWhitelist:
                              - group: '*'
                                kind: '*'
                          syncWindows:
                              - kind: allow
                                schedule: '* * * * *'
                                duration: 1h
                                applications:
                                    - '*'
                                manualSync: true
                    extraArgs:
                        - --app-state-cache-expiration
                        - 1s
                        - --default-cache-expiration
                        - 1s
                        - --oidc-cache-expiration
                        - 1s
                repoServer:
                    extraArgs:
                        - --default-cache-expiration
                        - 1s
                        - --repo-cache-expiration
                        - 1s
                        - --revision-cache-expiration
                        - 1s
        repoURL: >-
            https://argoproj.github.io/argo-helm
        targetRevision: '3.26.0'
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
        retry:
            backoff:
                duration: 5s
                factor: 2
                maxDuration: 1m
        syncOptions:
            - PruneLast=true
            - CreateNamespace=true
            - ApplyOutOfSyncOnly=true